# Generated by Django 4.0.5 on 2023-02-01 08:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceRegisterUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('devicetype', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicebrand', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceuser', models.CharField(blank=True, max_length=200, null=True)),
                ('deviceos', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicemacaddress', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicenetworkadaptercompany', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceip', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicelocation', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceprocessor', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceserialnumber', models.CharField(blank=True, max_length=1500, null=True)),
                ('devicecostofpurchase', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceyearofpurchase', models.CharField(blank=True, max_length=1500, null=True)),
                ('deviceid', models.CharField(blank=True, max_length=1500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('edited_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-edited_at', '-created_at'],
            },
        ),
    ]
