# Generated by Django 4.0.5 on 2023-02-02 04:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersarea', '0002_uploadeddevicedata'),
    ]

    operations = [
        migrations.RenameField(
            model_name='uploadeddevicedata',
            old_name='user',
            new_name='username',
        ),
        migrations.AlterField(
            model_name='uploadeddevicedata',
            name='mainfile',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
