# Generated by Django 4.0.5 on 2023-02-02 04:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('membersarea', '0003_rename_user_uploadeddevicedata_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='uploadeddevicedata',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='uploadeddevicedata',
            name='username',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
