# Generated by Django 4.0.5 on 2023-02-02 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersarea', '0006_rename_devicelocation_deviceregisterupload_devicemultiplepacket_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='devicelocation',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
        migrations.AddField(
            model_name='deviceregisterupload',
            name='devicetype',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
