# Generated by Django 4.0.5 on 2023-02-05 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('membersarea', '0010_deviceregisterupload_deviceworkingcondition'),
    ]

    operations = [
        migrations.AddField(
            model_name='deviceregisterupload',
            name='deviceusedepartment',
            field=models.CharField(blank=True, max_length=1500, null=True),
        ),
    ]
