# Generated by Django 4.0.5 on 2023-01-28 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('useronboard', '0002_rename_usersignup_signupform'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='signupform',
            options={'ordering': ['-edited_at', '-created_at']},
        ),
    ]
